[package]
name = "tdb"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
sha1 = "0.10.5"
serde = { version = "1.0.166", features = ["derive"] }
bincode = "1.3.3"
libflate = "2.0.0"
timed = { git = "https://github.com/copiumnicus/timed.git" }
